apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-ebs-pv
spec:
  capacity:
    storage: 3Gi
  volumeMode: Block
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-01fb60286d701b19c
    fsType: ext4   # Filesystem type
